services:
  - type: worker
    name: politcol-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -u main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
